# org: github.com/YourOnly-One

#custom: ["https://im.youronly.one/p/gift/?retribute", "https://paypal.me/yukino"]

#community_bridge: community_bridge_username
#github: [techmagus]
#issuehunt: issuehunt_username
#ko_fi: ko_fi_username
#liberapay: youronlyone
#open_collective: open_collective_username
#otechie: otechie_username
#patreon: patreon_username
#tidelift: tidelift_package_name
